# Generated by Django 3.2.12 on 2022-12-30 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='apply_link',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='is_active',
        ),
    ]
