# Generated by Django 4.1.4 on 2023-01-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_form_link', models.URLField(blank=True, default='#', null=True)),
                ('intro_video_link', models.URLField(blank=True, default='#', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, default='Image/profile1.png', null=True, upload_to='Partners')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='Image/hero-area.jpg', null=True, upload_to='Slider')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supported_By',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='Image/hero-area.jpg', null=True, upload_to='Supported_By')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('facebook_link', models.URLField(blank=True, default='raiseb.recb.ac.in', max_length=1000, null=True)),
                ('twitter_link', models.URLField(blank=True, default='raiseb.recb.ac.in', max_length=1000, null=True)),
                ('linkedin_link', models.URLField(blank=True, default='raiseb.recb.ac.in', max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, default='Image/profile1.png', null=True, upload_to='Team')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
