# Generated by Django 3.2.12 on 2022-12-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubation', '0002_alter_intro_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro_video',
            name='video',
            field=models.FileField(blank=True, default='Intro_video/profile1.png', null=True, upload_to='Intro_video'),
        ),
    ]
