# Generated by Django 3.2.12 on 2022-12-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubation', '0003_alter_intro_video_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('facebook', models.URLField(blank=True, default='#', max_length=1000, null=True)),
                ('twitter', models.URLField(blank=True, default='#', max_length=1000, null=True)),
                ('linkedin', models.URLField(blank=True, default='#', max_length=1000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, default='Image/profile1.png', null=True, upload_to='Testimonials')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='intro_video',
            name='video',
            field=models.FileField(blank=True, default='Image/profile1.png', null=True, upload_to='Intro_video'),
        ),
    ]
